<?php

namespace App\Models\Common;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    use HasFactory;

    protected $fillable = [
        "link_type",
        "link_id"
    ];
    public $timestamps = false;
    public function getNameAttribute(){
        return $this->button->name;
    }
    public function getLinkAttribute(){
        return $this->button->link;
    }
    public function button()
    {
        return $this->morphOne(Buttons::class, "button");
    }

    public function __get($key)
    {

        if ($key == "name") {
            return $this->button["name^ru"];
        }
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
